services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  grabeklis:
    build:
      context: .
    container_name: grabeklis
    env_file:
      - .env
    depends_on:
      - mongodb
